service: s3-file-uploader

provider:
  name: aws
  runtime: nodejs12.x
  region: use-west-1

custom:
  fileUploadBucketName: ${self:service}-bucket-${self:provider.stage}

resouces:
  Resources:
    FileBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.fileUploadBucketName}
        AccessControl: PublicRead

